CREATE TABLE Admins (
    AdminID INT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(50) NOT NULL,
    NICNumber VARCHAR(15) NOT NULL UNIQUE
);